# Pre-commit hooks configuration for AI Whisperers Website
# See https://pre-commit.com for more information

repos:
  # Basic file cleanup and validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Essential cleanup hooks
      - id: trailing-whitespace
        description: Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        description: Ensure files end with newline
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-added-large-files
        description: Prevent large files from being committed
        args: ['--maxkb=500']
      
      # File format validation
      - id: check-yaml
        description: Validate YAML files
        files: \.(yaml|yml)$
        exclude: ^node_modules/
      - id: check-json
        description: Validate JSON files
        files: \.json$
        exclude: ^(node_modules/|package-lock\.json$)
      - id: check-toml
        description: Validate TOML files
        files: \.toml$
      
      # Security checks
      - id: detect-private-key
        description: Detect private keys
      - id: check-case-conflict
        description: Check for case conflicts on case-insensitive filesystems

  # Prettier for code formatting (TypeScript, JavaScript, CSS, etc.)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        description: Format code with Prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|md)$
        exclude: ^(node_modules/|\.next/|out/|build/|coverage/|local-reports/)
        additional_dependencies:
          - prettier@3.0.0
        
  # ESLint for code quality (integrates with existing config)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.12.0
    hooks:
      - id: eslint
        description: Lint with ESLint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^(node_modules/|\.next/|out/|build/|coverage/|scripts/)
        additional_dependencies:
          - eslint@^9.0.0
          - eslint-config-next@15.4.4
          - "@eslint/eslintrc@^3.0.0"
          - typescript@5.9.2
        args: [--fix, --config, eslint.config.mjs]

  # Security: Gitleaks for secrets detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        description: Detect secrets with gitleaks
        stages: [commit]

  # Optional: Prevent commits to main branch (can be disabled)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        description: Don't commit to main branch
        args: ['--branch=main', '--branch=master']
        stages: [commit]

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'