# Render.com Blueprint for AI Whisperers Platform
# Docker deployment for proper Next.js standalone mode support

services:
  - type: web
    name: ai-whisperers-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: ai-whisperers-web
          property: host
      # OAuth providers (configure manually in Render dashboard)
      # - key: GOOGLE_CLIENT_ID
      #   value: your-google-client-id
      # - key: GOOGLE_CLIENT_SECRET
      #   value: your-google-client-secret
      # - key: GITHUB_CLIENT_ID
      #   value: your-github-client-id
      # - key: GITHUB_CLIENT_SECRET
      #   value: your-github-client-secret