meta:
  title: "Services - AI Education & Consulting | AI Whisperers"
  description: "Comprehensive AI education courses and consulting services to transform your business with artificial intelligence."
  keywords:
    - "AI services"
    - "AI consulting"
    - "artificial intelligence courses"
    - "business transformation"
    - "AI implementation"

hero:
  title: "AI Education & Consulting Services"
  subtitle: "Transform your business and career with artificial intelligence"
  description: "We offer comprehensive AI education and consulting services designed to help individuals and organizations harness the power of artificial intelligence."

services:
  - title: "AI Foundation Courses"
    description: "Comprehensive courses from beginner to expert level"
    features:
      - "4 complete course levels"
      - "65+ hours of content"
      - "Hands-on projects"
      - "Industry certifications"
    price: "From $299"
    cta: "View Courses"
    
  - title: "Corporate AI Training"
    description: "Custom AI training programs for your organization"
    features:
      - "Tailored curricula"
      - "Team workshops"
      - "Implementation support"
      - "Ongoing consultation"
    price: "Custom Pricing"
    cta: "Contact Sales"
    
  - title: "AI Consulting"
    description: "Strategic AI implementation for your business"
    features:
      - "AI strategy development"
      - "Technology assessment"
      - "Implementation roadmaps"
      - "Performance optimization"
    price: "Starting at $5,000"
    cta: "Schedule Consultation"
    
  - title: "1-on-1 Mentoring"
    description: "Personal AI mentoring and career guidance"
    features:
      - "Expert mentorship"
      - "Career planning"
      - "Project reviews"
      - "Interview preparation"
    price: "$150/hour"
    cta: "Book Session"

benefits:
  - title: "Proven Expertise"
    description: "Our instructors are industry professionals with real-world AI experience"
  - title: "Practical Approach"
    description: "Learn through hands-on projects and real business applications"
  - title: "Flexible Learning"
    description: "Self-paced courses and flexible consulting arrangements"
  - title: "Ongoing Support"
    description: "Continuous support and updates as AI technology evolves"

cta:
  title: "Ready to Start Your AI Journey?"
  description: "Choose the service that best fits your needs and begin transforming your career or business with AI."
  button: "Get Started Today"