name: Docker Build and Test

on:
  push:
    branches: [ main, dockerization ]
  pull_request:
    branches: [ main ]

# Prevent pushing build artifacts to repository
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Don't persist credentials to prevent accidental artifact commits
        persist-credentials: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ai-whisperers-app:${{ github.sha }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # Prevent build artifacts from being committed
        outputs: type=docker,dest=/dev/null

    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Test health endpoint
      run: |
        docker-compose up -d app
        sleep 10
        curl -f http://localhost:3000/api/health || exit 1
        docker-compose down

    - name: Clean up Docker artifacts
      if: always()
      run: |
        docker-compose down -v --remove-orphans
        docker system prune -f
